### ISSUE TITLE
SPF change detection

### ISSUE THREAD

**Issue by schack-storytel** [domainaware/checkdmarc#15]
Would it be possible to add some sort of hash to the get_spf_record function result, thereby enabling really easy change detection.
Some smart sorting would have to be done before calculating a hash.
Example: dsv.com contains an a:mail.dsv.com that returns a collection of ip addresses in random order.

**Comment by seanthegeek** [comment]
I'll put it on my to do list :)

**Comment by malvidin** [comment]
For returned values that can be returned in any order, I recommend sorting beforehand rather than calculating a hash. I've only run into this issue for MX results, but I haven't checked the order that TXT records for domains with multiple SPF records are returned.

On the topic of change detection, DNS timeouts are returned with precision that are unlikely to be duplicated: "The DNS operation timed out after 6.002326726913452 seconds"

**Comment by malvidin** [comment]
To detect changes, I use jsondiff on the results that checkdmarc produces. I have also hashed the result and compared to previous hashes, but for me, that caused more issues than it solved.

I also strip ' after #.### seconds" from any DNS timeout errors, but warnings can also be ignored either before or after a diff is performed.
