### ISSUE TITLE
DNS timeout on certain domains

### ISSUE THREAD

**Issue by schack** [domainaware/checkdmarc#40]
When running:
checkdmarc accenture.com
some sort of timeout error occurs.
--cut--
  "spf": {
    "record": "v=spf1 include:_spf1.exchange.accenture.com include:_spf2.exchange.accenture.com include:_spf3.exchange.accenture.com include:spf.protection.outlook.com -all",
    "valid": false,
    "warnings": [],
    "error": "The DNS operation timed out after 6.0 seconds"
  },
  "dmarc": {
    "record": null,
    "valid": false,
    "location": null,
    "error": "The DNS operation timed out after 6.0 seconds"
  }
--cut--
edit: What I find strange is to return an SPF error and the actual SPF record, in addition the DMARC record is missing

**Comment by seanthegeek** [comment]
I'm not able to reproduce this.

’’’
checkdmarc accenture.com
’’’

Returns full results almost instantly for me. 
In your results, it's showing the SPF record, because the first DNS query to get the actual record worked, but every DNS query after that (to get the included SPF records and the DMARC record timed out.

Please try on a different network. Sometimes firewalls or other security appliances will man-in-the-middle DNS responses.

**Comment by schack** [comment]
True, now it works again, but I've seen this domain "hang" several times. 
Even after having "refreshed" the DNS server I use manually before running checkdmarc.

**Comment by schack** [comment]
You're right, this is not checkdmarc related, the domain hangs when using nslookup as well.
Sorry about the noise :-(
