### ISSUE TITLE
missing raise

### ISSUE THREAD

**Issue by magicjohnson** [domainaware/checkdmarc#72]
Hey!
I was looking at the code and it looks  that `raise` word is missing here.

https://github.com/domainaware/checkdmarc/blob/2d8efc6d92512ea233df7286aee3be010add1164/checkdmarc.py#L881

**Comment by NicoIsapro** [comment]
I would say in this particular case when the DNS query of TXT entries of **_dmarc.x.com** is failing and then the code try to query DNS TXT entries of the domain **x.com** to know if it exists, it would make sense to raise the error because some remaining errors such as `dns.resolver.YXDOMAIN` are not covered.
Even we already catch the main probability case of "The domain x.com does not exist".
Btw, I tested this particular case and it results that missing the `raise` word does not throw any error or crash.

@seanthegeek Tell us what you would like to do, I already prepared a branch with the `raise` word in case you are busy
